### ISSUE TITLE
UnicodeDecodeError after nlp = English(data_dir=data_dir)

### ISSUE THREAD

**Issue by kochkinael** [honnibal/spaCy#160]
Hello,
I am using Anaconda Python 3.4 w Spyder on Mac
Trying to go through the very first tutorial:
from spacy.en import English, LOCAL_DATA_DIR
import os
data_dir = os.environ.get('SPACY_DATA', LOCAL_DATA_DIR)
nlp = English(data_dir=data_dir)

And I get this:

Traceback (most recent call last):

  File "<ipython-input-14-aed6209adf97>", line 6, in <module>
    nlp = English(data_dir=data_dir)

  File "/Users/Helen/anaconda/lib/python3.4/site-packages/spacy/language.py", line 192, in __init__
    vocab = self.default_vocab(data_dir)

  File "/Users/Helen/anaconda/lib/python3.4/site-packages/spacy/language.py", line 147, in default_vocab
    get_lex_attr=get_lex_attr)

  File "spacy/vocab.pyx", line 48, in spacy.vocab.Vocab.from_dir (spacy/vocab.cpp:3084)

  File "/Users/Helen/anaconda/lib/python3.4/site-packages/spacy/lemmatizer.py", line 22, in from_dir
    rules = json.load(open(path.join(data_dir, 'vocab', 'lemma_rules.json')))

  File "/Users/Helen/anaconda/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 540: ordinal not in range(128)

Could you advise how to fix it?
Thank you

**Comment by honnibal** [comment]
Hmm.

What version has that downloaded? Is there a way to get that from Anaconda?

That line is different in the most recent version (it calls `codecs.open`).

**Comment by kochkinael** [comment]
I thought I had 0.97, but it turned out to be 0.94 - I installed it using: conda install spacy
Ok, I tried to upgrade it using pip, and I got this when I tried to download data:

Error while finding spec for 'spacy.en.download' (<class 'ValueError'>: cymem.cymem.Pool has the wrong size, try recompiling)

I tried uninstalling and installing again, but I get same error.

**Comment by Ejhfast** [comment]
After upgrading to 0.97, I'm getting the same error:

`cymem.cymem.Pool has the wrong size, try recompiling`

Uninstalling and reinstalling didn't help, either.

**Comment by henningpeters** [comment]
Can you try to get a complete fresh install (e.g., new environment) via conda, not sure how reliable it is to mix conda and pip. Following steps should work:

```conda create -n test python==3.4```
```source activate test```
```conda install -c https://conda.anaconda.org/spacy spacy```
```python -m spacy.en.download all```

If that this fails it would be great if you could report some details of your system, e.g., with following script: https://gist.github.com/henningpeters/22d2aa6979916572e649

**Comment by Ejhfast** [comment]
Just to clarify, I don't use conda, so this is also failing on a purely pip-based system.

Your debug script also fails for me with:

Traceback (most recent call last):
  File "debug.py", line 90, in <module>
    print("locations.site_config_files", pip.locations.site_config_files)
AttributeError: 'module' object has no attribute 'site_config_files'

Thanks for the help.

**Comment by kochkinael** [comment]
I tried what you suggested but got same error again.
Here's details obtained using the script you provided:

--- python ---
build default
compiler GCC 4.2.1 (Apple Inc. build 5577)
implementation CPython
version 3.4.3
branch 
revision 
has_64bits True
path ['', '/Users/Helen/anaconda/lib/python3.4/site-packages/setuptools-18.4-py3.4.egg', '/Users/Helen/anaconda/lib/python3.4/site-packages/gensim-0.12.2-py3.4-macosx-10.5-x86_64.egg', '/Users/Helen/anaconda/lib/python3.4/site-packages/smart_open-1.3.0-py3.4.egg', '/Users/Helen/anaconda/lib/python3.4/site-packages/bz2file-0.98-py3.4.egg', '/Users/Helen/anaconda/lib/python3.4/site-packages/httpretty-0.8.6-py3.4.egg', '/Users/Helen/anaconda/lib/python3.4/site-packages/Theano-0.7.0-py3.4.egg', '/Users/Helen/anaconda/lib/python34.zip', '/Users/Helen/anaconda/lib/python3.4', '/Users/Helen/anaconda/lib/python3.4/plat-darwin', '/Users/Helen/anaconda/lib/python3.4/lib-dynload', '/Users/Helen/anaconda/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg', '/Users/Helen/anaconda/lib/python3.4/site-packages', '/Users/Helen/anaconda/lib/python3.4/site-packages/aeosa', '/Users/Helen/anaconda/lib/python3.4/site-packages/IPython/extensions', '/Users/Helen/.ipython']
env: PYTHONPATH None

--- system ---
system Darwin
release Elenas-MBP
version 14.5.0
machine Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64
processor x86_64
mac_ver 10.10.5

--- pip ---
version 7.1.2
path ['/Users/Helen/anaconda/lib/python3.4/site-packages/pip']
locations.bin_py /Users/Helen/anaconda/bin
locations.bin_user /Users/Helen/.local/lib/python3.4/site-packages/bin
locations.site_config_files ['/Library/Application Support/pip/pip.conf']
locations.src_prefix /Users/Helen/Documents/PhD/Tutorials, tests etc/src
locations.user_dir /Users/Helen
locations.user_site /Users/Helen/.local/lib/python3.4/site-packages
locations.running_under_virtualenv False
locations.virtualenv_no_global None
locations.installed_distributions [setuptools 18.4 (/Users/Helen/anaconda/lib/python3.4/site-packages/setuptools-18.4-py3.4.egg), gensim 0.12.2 (/Users/Helen/anaconda/lib/python3.4/site-packages/gensim-0.12.2-py3.4-macosx-10.5-x86_64.egg), smart-open 1.3.0 (/Users/Helen/anaconda/lib/python3.4/site-packages/smart_open-1.3.0-py3.4.egg), bz2file 0.98 (/Users/Helen/anaconda/lib/python3.4/site-packages/bz2file-0.98-py3.4.egg), httpretty 0.8.6 (/Users/Helen/anaconda/lib/python3.4/site-packages/httpretty-0.8.6-py3.4.egg), Theano 0.7.0 (/Users/Helen/anaconda/lib/python3.4/site-packages/Theano-0.7.0-py3.4.egg), Sphinx 1.3.1 (/Users/Helen/anaconda/lib/python3.4/site-packages/Sphinx-1.3.1-py3.4.egg), abstract-rendering 0.5.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), alabaster 0.7.6 (/Users/Helen/anaconda/lib/python3.4/site-packages), appnope 0.1.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), argcomplete 0.8.9 (/Users/Helen/anaconda/lib/python3.4/site-packages), astropy 1.0.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), Babel 2.1.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), bcolz 0.9.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), beautifulsoup4 4.3.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), binstar 0.11.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), bitarray 0.8.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), blaze 0.8.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), blz 0.6.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), bokeh 0.9.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), boto 2.38.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), Bottleneck 1.0.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), certifi 14.5.14 (/Users/Helen/anaconda/lib/python3.4/site-packages), cffi 1.1.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), cloudpickle 0.1.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), clyent 0.3.4 (/Users/Helen/anaconda/lib/python3.4/site-packages), colorama 0.3.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), conda 3.18.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), conda-build 1.14.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), conda-env 2.4.4 (/Users/Helen/anaconda/lib/python3.4/site-packages), configobj 5.0.6 (/Users/Helen/anaconda/lib/python3.4/site-packages), cryptography 0.9.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), cymem 1.30 (/Users/Helen/anaconda/lib/python3.4/site-packages), Cython 0.22.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), cytoolz 0.7.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), datashape 0.4.5 (/Users/Helen/anaconda/lib/python3.4/site-packages), decorator 4.0.4 (/Users/Helen/anaconda/lib/python3.4/site-packages), docutils 0.12 (/Users/Helen/anaconda/lib/python3.4/site-packages), fastcache 1.0.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), Flask 0.10.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), greenlet 0.4.7 (/Users/Helen/anaconda/lib/python3.4/site-packages), h5py 2.5.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), headers-workaround 0.18 (/Users/Helen/anaconda/lib/python3.4/site-packages), idna 2.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), ipykernel 4.1.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), ipython 4.0.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), ipython-genutils 0.1.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), itsdangerous 0.24 (/Users/Helen/anaconda/lib/python3.4/site-packages), jdcal 1.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), jedi 0.9.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), Jinja2 2.8 (/Users/Helen/anaconda/lib/python3.4/site-packages), jsonschema 2.4.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), jupyter-client 4.1.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), jupyter-core 4.0.6 (/Users/Helen/anaconda/lib/python3.4/site-packages), llvmlite 0.5.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), lxml 3.4.4 (/Users/Helen/anaconda/lib/python3.4/site-packages), MarkupSafe 0.23 (/Users/Helen/anaconda/lib/python3.4/site-packages), matplotlib 1.4.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), mistune 0.7.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), mock 1.0.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), multipledispatch 0.4.7 (/Users/Helen/anaconda/lib/python3.4/site-packages), murmurhash 0.24 (/Users/Helen/anaconda/lib/python3.4/site-packages), nbconvert 4.0.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), nbformat 4.0.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), networkx 1.9.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), nltk 3.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), nose 1.3.7 (/Users/Helen/anaconda/lib/python3.4/site-packages), notebook 4.0.6 (/Users/Helen/anaconda/lib/python3.4/site-packages), numba 0.19.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), numexpr 2.4.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), numpy 1.10.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), odo 0.3.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), openpyxl 1.8.5 (/Users/Helen/anaconda/lib/python3.4/site-packages), pandas 0.16.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), path.py 0.0.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), patsy 0.3.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), pep8 1.6.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), pexpect 3.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), pickleshare 0.5 (/Users/Helen/anaconda/lib/python3.4/site-packages), Pillow 2.8.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), pip 7.1.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), plac 0.9.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), ply 3.6 (/Users/Helen/anaconda/lib/python3.4/site-packages), preshed 0.43 (/Users/Helen/anaconda/lib/python3.4/site-packages), psutil 3.2.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), ptyprocess 0.5 (/Users/Helen/anaconda/lib/python3.4/site-packages), py 1.4.27 (/Users/Helen/anaconda/lib/python3.4/site-packages), pyasn1 0.1.7 (/Users/Helen/anaconda/lib/python3.4/site-packages), pycosat 0.6.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), pycparser 2.14 (/Users/Helen/anaconda/lib/python3.4/site-packages), pycrypto 2.6.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), pycurl 7.19.5.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), pyflakes 1.0.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), Pygments 2.0.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), pyOpenSSL 0.15.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), pyparsing 2.0.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), pytest 2.7.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), python-dateutil 2.4.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), pytz 2015.6 (/Users/Helen/anaconda/lib/python3.4/site-packages), PyYAML 3.11 (/Users/Helen/anaconda/lib/python3.4/site-packages), pyzmq 14.7.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), qtconsole 4.1.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), redis 2.10.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), requests 2.8.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), rope-py3k 0.9.4-1 (/Users/Helen/anaconda/lib/python3.4/site-packages), runipy 0.1.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), scikit-image 0.11.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), scikit-learn 0.16.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), scipy 0.15.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), simplegeneric 0.8.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), six 1.10.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), snowballstemmer 1.2.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), sockjs-tornado 1.0.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), spacy 0.97 (/Users/Helen/anaconda/lib/python3.4/site-packages), sphinx-rtd-theme 0.1.7 (/Users/Helen/anaconda/lib/python3.4/site-packages), spyder 2.3.7 (/Users/Helen/anaconda/lib/python3.4/site-packages), SQLAlchemy 1.0.5 (/Users/Helen/anaconda/lib/python3.4/site-packages), statsmodels 0.6.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), sympy 0.7.6 (/Users/Helen/anaconda/lib/python3.4/site-packages), tables 3.2.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), terminado 0.5 (/Users/Helen/anaconda/lib/python3.4/site-packages), text-unidecode 1.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), thinc 3.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), toolz 0.7.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), tornado 4.2.1 (/Users/Helen/anaconda/lib/python3.4/site-packages), traitlets 4.0.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), ujson 1.33 (/Users/Helen/anaconda/lib/python3.4/site-packages), Unidecode 0.4.17 (/Users/Helen/anaconda/lib/python3.4/site-packages), Werkzeug 0.10.4 (/Users/Helen/anaconda/lib/python3.4/site-packages), wget 2.2 (/Users/Helen/anaconda/lib/python3.4/site-packages), wheel 0.26.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), xlrd 0.9.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), XlsxWriter 0.7.3 (/Users/Helen/anaconda/lib/python3.4/site-packages), xlwings 0.3.5 (/Users/Helen/anaconda/lib/python3.4/site-packages), xlwt 1.0.0 (/Users/Helen/anaconda/lib/python3.4/site-packages), appscript 1.0.1 (/Users/Helen/anaconda/lib/python3.4/site-packages/aeosa)]

--- conda ---
version 3.18.3
config.add_pip_as_python_dependency True
config.default_prefix /Users/Helen/anaconda
config.default_python 3.4
config.use_pip True
config.root_dir /Users/Helen/anaconda
config.user_rc_path /Users/Helen/.condarc
config.platform osx
config.arch_name x86_64
config.envs_dirs ['/Users/Helen/anaconda/envs']
config.pkgs_dirs ['/Users/Helen/anaconda/pkgs']
$ conda list # packages in environment at /Users/Helen/anaconda: # _license 1.1 py34_0 abstract-rendering 0.5.1 np19py34_0 alabaster 0.7.6 py34_0 anaconda 2.3.0 np19py34_0 appnope 0.1.0 py34_0 appscript 1.0.1 py34_0 argcomplete 0.8.9 py34_0 astropy 1.0.3 np19py34_0 babel 2.1.1 py34_0 bcolz 0.9.0 np19py34_0 beautiful-soup 4.3.2 py34_0 beautifulsoup4 4.3.2 <pip> binstar 0.11.0 py34_0 bitarray 0.8.1 py34_0 blaze 0.8.0 <pip> blaze-core 0.8.0 np19py34_0 blz 0.6.2 np19py34_1 bokeh 0.9.0 np19py34_0 boto 2.38.0 py34_0 bottleneck 1.0.0 np19py34_0 bz2file 0.98 <pip> certifi 14.05.14 py34_0 cffi 1.1.0 py34_0 cloudpickle 0.1.0 py34_0 clyent 0.3.4 py34_0 colorama 0.3.3 py34_0 conda 3.18.3 py34_0 conda-build 1.14.1 py34_0 conda-env 2.4.4 py34_0 configobj 5.0.6 py34_0 cryptography 0.9.1 py34_0 curl 7.43.0 0 cymem 1.11 py34_0 cython 0.22.1 py34_0 cytoolz 0.7.3 py34_0 datashape 0.4.5 np19py34_0 decorator 4.0.4 py34_0 docutils 0.12 py34_0 dynd-python 0.6.5 np19py34_0 fastcache 1.0.2 py34_0 flask 0.10.1 py34_1 freetype 2.5.5 0 gensim 0.12.2 <pip> greenlet 0.4.7 py34_0 h5py 2.5.0 np19py34_3 hdf5 1.8.15.1 1 headers-workaround 0.18 <pip> headers_workaround 0.18 py34_0 httpretty 0.8.6 <pip> idna 2.0 py34_0 ipykernel 4.1.1 py34_0 ipython 4.0.0 py34_1 ipython-genutils 0.1.0 <pip> ipython-notebook 4.0.4 py34_0 ipython-qtconsole 3.2.0 py34_0 ipython_genutils 0.1.0 py34_0 itsdangerous 0.24 py34_0 jdcal 1.0 py34_0 jedi 0.9.0 py34_0 jinja2 2.8 py34_0 jpeg 8d 1 jsonschema 2.4.0 py34_0 jupyter-client 4.1.1 <pip> jupyter-core 4.0.6 <pip> jupyter_client 4.1.1 py34_0 jupyter_core 4.0.6 py34_0 launcher 1.0.0 3 libdynd 0.6.5 0 libpng 1.6.17 0 libsodium 0.4.5 0 libtiff 4.0.2 1 libxml2 2.9.2 0 libxslt 1.1.28 2 llvmlite 0.5.0 py34_0 lxml 3.4.4 py34_0 markupsafe 0.23 py34_0 matplotlib 1.4.3 np19py34_2 mistune 0.7.1 py34_0 mock 1.0.1 py34_0 multipledispatch 0.4.7 py34_0 murmurhash 0.24 py34_0 nbconvert 4.0.0 py34_0 nbformat 4.0.1 py34_0 networkx 1.9.1 py34_0 nltk 3.0.3 np19py34_0 node-webkit 0.10.1 0 nose 1.3.7 py34_0 notebook 4.0.6 py34_0 numba 0.19.1 np19py34_0 numexpr 2.4.3 np19py34_0 numpy 1.10.1 py34_0 odo 0.3.2 np19py34_0 openpyxl 1.8.5 py34_0 openssl 1.0.2d 0 pandas 0.16.2 np19py34_0 path.py 8.1.2 py34_0 patsy 0.3.0 np19py34_0 pep8 1.6.2 py34_0 pexpect 3.3 py34_0 pickleshare 0.5 py34_0 pillow 2.8.2 py34_0 pip 7.1.2 py34_0 plac 0.9.1 py34_0 ply 3.6 py34_0 preshed 0.42 py34_0 psutil 3.2.2 py34_0 ptyprocess 0.5 py34_0 py 1.4.27 py34_0 pyasn1 0.1.7 py34_0 pycosat 0.6.1 py34_0 pycparser 2.14 py34_0 pycrypto 2.6.1 py34_0 pycurl 7.19.5.1 py34_2 pyflakes 1.0.0 py34_0 pygments 2.0.2 py34_0 pyopenssl 0.15.1 py34_1 pyparsing 2.0.3 py34_0 pyqt 4.11.4 py34_0 pytables 3.2.0 np19py34_0 pytest 2.7.1 py34_0 python 3.4.3 2 python-dateutil 2.4.2 py34_0 python.app 1.2 py34_4 pytz 2015.6 py34_0 pywget 2.2 py34_0 pyyaml 3.11 py34_1 pyzmq 14.7.0 py34_1 qt 4.8.7 1 qtconsole 4.1.0 py34_0 readline 6.2 2 redis 2.6.9 0 redis-py 2.10.3 py34_0 requests 2.8.1 py34_0 rope 0.9.4 py34_1 rope-py3k-0.9.4 1 <pip> runipy 0.1.3 py34_0 scikit-image 0.11.3 np19py34_0 scikit-learn 0.16.1 np19py34_0 scipy 0.15.1 np19py34_0 setuptools 18.4 py34_0 simplegeneric 0.8.1 py34_0 sip 4.16.9 py34_0 six 1.10.0 py34_0 smart-open 1.3.0 <pip> snowballstemmer 1.2.0 py34_0 sockjs-tornado 1.0.1 py34_0 spacy 0.97 py34_0 sphinx 1.3.1 py34_0 sphinx-rtd-theme 0.1.7 <pip> sphinx_rtd_theme 0.1.7 py34_0 spyder 2.3.7 py34_1 spyder-app 2.3.7 py34_0 sqlalchemy 1.0.5 py34_0 sqlite 3.8.4.1 1 statsmodels 0.6.1 np19py34_0 sympy 0.7.6 py34_0 tables 3.2.0 <pip> terminado 0.5 py34_1 text-unidecode 1.0 py34_0 theano 0.7.0 <pip> thinc 3.3 py34_0 tk 8.5.18 0 toolz 0.7.2 py34_0 tornado 4.2.1 py34_1 traitlets 4.0.0 py34_0 ujson 1.33 py34_0 unidecode 0.4.17 py34_0 werkzeug 0.10.4 py34_0 wget 2.2 <pip> wheel 0.26.0 py34_1 xlrd 0.9.3 py34_0 xlsxwriter 0.7.3 py34_0 xlwings 0.3.5 py34_0 xlwt 1.0.0 py34_0 xz 5.0.5 0 yaml 0.1.6 0 zeromq 4.1.3 0 zlib 1.2.8 0

--- compiler ---
env: CC None
env: CXX None
$ gcc Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
$ g++ Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
$ clang Apple LLVM version 7.0.0 (clang-700.1.76) Target: x86_64-apple-darwin14.5.0 Thread model: posix
$ cython Cython version 0.22.1

**Comment by henningpeters** [comment]
@Ejhfast after upgrade did you call ```python -m spacy.en.download all --force```? New spaCy releases are typically not compatible with older models.

The debug script is calling some undocumented pip stuff. It's not yet properly tested across many environments yet. It would be great if you could help make adjustments to make it work in yours.

@kochkinael It doesn't look like you created and activated a new/clean conda environment (the first two steps), otherwise I you wouldn't have that many unrelated packages installed in it.

**Comment by Ejhfast** [comment]
`python -m spacy.en.download all --force` also fails with the same error:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/Library/Python/2.7/site-packages/spacy/en/__init__.py", line 5, in <module>
    from ..language import Language
  File "/Library/Python/2.7/site-packages/spacy/language.py", line 10, in <module>
    from .tokenizer import Tokenizer
  File ".env/lib/python3.4/site-packages/cymem/cymem.pxd", line 1, in init spacy.tokenizer (spacy/tokenizer.cpp:9218)
ValueError: cymem.cymem.Pool has the wrong size, try recompiling

And sure, I'll take a look at the pip stuff and dig into what's going wrong.

**Comment by honnibal** [comment]
That `cymem` error is my bad — I updated the `cymem` package last night and haven't pushed a new version of spaCy yet. It'll be fixed within a few hours.

**Comment by honnibal** [comment]
Pushed v0.98. Try now.

**Comment by kochkinael** [comment]
It worked! I only tried first example so far, but it worked! Thank you so much for being so professional and fast!
